name: Deploy to Server

on:
  push:
    branches:
      - master
    paths: 
      - 'src/**'
      - 'public/**'
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Clone repository
      uses: actions/checkout@main

    - name: Set up pnpm
      uses: pnpm/action-setup@master
      with:
        version: latest

    - name: Build project
      run: |
        pnpm install
        pnpm run build

    - name: Move build to server
      uses: appleboy/scp-action@master
      with:
        host: arch-fan.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: dist/
        target: ~/docker/nginx/www/
        
    - name: Clean folder at server
      uses: appleboy/ssh-action@master
      with:
        host: arch-fan.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          rm -rf ~/docker/nginx/www/portfolio/*
          mv ~/docker/nginx/www/dist ~/docker/nginx/www/portfolio
