name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Set up project
      uses: actions/checkout@main

    - name: Set up bun
      uses: pnpm/action-setup@master
      with:
        version: latest

    - name: Build project
      run: |
        pnpm install
        pnpm run build

    - name: Clean folder
      uses: appleboy/ssh-action@master
      with:
        host: arch-fan.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          rm -rf /www/portfolio/*

    - name: Copy build to server
      uses: appleboy/scp-action@master
      with:
        host: arch-fan.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "dist/"
        target: /www/portfolio/